# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ryan D'Mello
email: rydmello@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Ryan D'Mello's academic website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rydmel.github.com" # the base hostname & protocol for your site
future: true # allows future dated posts



# Build settings
markdown: kramdown

# Other Options
permalink: blog/:year/:month/:title/
excerpt_separator: "<!--more-->"
